Documentation proposal
cnumr/ecoCode pull request #33
Opened 2022-02-25 15:15 UTC by obeone

Hi !

Here is a collaborative proposal from the Android plugin’s team to rethink presentation and documentation about ecoCode.

Feel free to comment, edit etc !

2022-03-10 20:14 UTC, obeone commented on README.md
> +[4 different SonarQube plugins](sonarqube-plugin-greenit/) are available right now:
En effet, mais il est aussi possible de les utiliser séparément, et quelque part, en terme d'eco-responsabilité, moins y a de code, moins ça consomme ;)

A mon sens, qu'on communique sur un plugin, surtout grand public/dev extérieur oui et c'est d'ailleurs pour ça que c'est le all-in-one mis en avant, mais techniquement ça en est finalement plusieurs, avec des approches parfois différentes.
Je pense a un exemple sur lequel je suis en ce moment même : Ceph est un storage.... qui propose plusieurs storages ;)

2022-03-10 20:16 UTC, glalloue requested changes

2022-03-10 20:16 UTC, glalloue commented on README.md
> +- [Olivier Le Goaër](https://olegoaer.perso.univ-pau.fr)
Voici la liste des entreprises à mentionner sur leur participation au projet : 

These companies have contributed to the success of the ecoCode project : 
- [Davidson Consulting](https://www.davidson.fr/)
- [Orange Business Services](https://www.orange-business.com/fr)
- [Snapp'](https://www.snapp.fr/)

2022-03-10 20:18 UTC, obeone commented on README.md
> +- [Olivier Le Goaër](https://olegoaer.perso.univ-pau.fr)
+ Université de Pau je pense, et dans ce cas il me semble qu'il faudrait indiquer les soutiens qui ont fourni des subventions.
En effet, ça me semble nécessaire

2022-03-10 20:19 UTC, glalloue commented on README.md
> +[4 different SonarQube plugins](sonarqube-plugin-greenit/) are available right now:
je suis d'accord avec toi
Etant donné qu'ici on est sur le README et donc sur la page d'accueil du projet, je pense qu'il faut quand même qu'on reste simple et qu'on ne rentre pas dans les détails de ce qu'il y a sous le capot. 
C'est pour ca que je trouve plus approprié de ne mentionner qu'un seul plugin (ce qui est la réalité en fait)

Et pourquoi pas mentionner le fait qu'on puisse les installer séparément dans le INSTALL plutôt (d'ailleurs je crois que c'est fait)

Qu'est-ce que tu en pense ?

2022-03-10 21:06 UTC, glalloue commented on README.md
> +- [Olivier Le Goaër](https://olegoaer.perso.univ-pau.fr)
c'est quoi que tu entends par subventions ? parce que le projet ecoCode en lui même n'a pas reçu de subvention a ce jour (pas côté cnumr toujours)

2022-03-10 21:17 UTC, obeone commented on README.md
> +- [Olivier Le Goaër](https://olegoaer.perso.univ-pau.fr)
La région Nouvelle-Aquitaine a soutenu financièrement Snapp' pour le développement initial de l'aspect Android 

https://www.ecocode.io/team

2022-03-11 08:19 UTC, glalloue commented on README.md
> +- [Olivier Le Goaër](https://olegoaer.perso.univ-pau.fr)
ok je n'avais pas cette info,
Donc on peut imaginer un texte comme celui-ci : 

---

They have contributed to the success of ecoCode :

- [Davidson Consulting](https://www.davidson.fr/)
- [Orange Business Services](https://www.orange-business.com/fr)
- [Snapp'](https://www.snapp.fr/)
- [Université de Pau et des Pays de l'Adour (UPPA)](https://www.univ-pau.fr/)

They supported the project : 

- [Région Nouvelle-Aquitaine](https://www.nouvelle-aquitaine.fr/)

2022-03-11 09:42 UTC, olegoaer commented on README.md
> +ecoCode is a collective project aiming the reduction the environmental footprint of IT at the software level. The goal of the project is to provide a curated list of static code analyzers to remove q
le fatware est la traduction de "obésiciel" (qui n'est pas tout à fait la même chose que bloatware). C'est un terme connu du GreenIT

2022-03-11 10:05 UTC, merged

2022-03-11 10:14 UTC, glalloue commented
@olegoaer : peux tu indiquer pourquoi tu as mergé avant la résolution des review stp? 
Est-ce que c'était par erreur et dans ce cas on fait un revert ?